### ISSUE TITLE
"Analyzer failed to build" on all recent runs

### ISSUE THREAD

**Issue by urvangjoshi** [tdaede/awcy#115]
See: https://arewecompressedyet.com/?job=wm_gm%402017-01-27T04%3A35%3A05.272Z

Errors/warnings in the log:

In file included from ../aom_dsp/dkboolreader.c:16:
In file included from ../aom_dsp/dkboolreader.h:27:
../aom/aomdx.h:133:3: error: redefinition of enumerator 'AOM_DECODER_CTRL_ID_MAX'
  AOM_DECODER_CTRL_ID_MAX,
  ^
../aom/aomdx.h:122:3: note: previous definition is here
  AOM_DECODER_CTRL_ID_MAX,
  ^
In file included from ../aom_dsp/dkboolreader.c:16:
In file included from ../aom_dsp/dkboolreader.h:31:
../av1/common/accounting.h:58:27: warning: redefinition of typedef 'Accounting' is a C11 feature [-Wtypedef-redefinition]
typedef struct Accounting Accounting;
                          ^
../aom/aomdx.h:44:27: note: previous definition is here
typedef struct Accounting Accounting;
                          ^
1 warning and 1 error generated.
ERROR:root:[31mcompiler frontend failed to generate LLVM bitcode, halting[0m
make[1]: *** [aom_dsp/dkboolreader.c.o] Error 1
make: *** [.DEFAULT] Error 2
-- Finished Analyzer Build --
Note: Analyzer errors will not prevent the run from completing.

**Comment by mbebenita** [comment]
This should be fixed shortly. I just rebased the analyzer.

**Comment by urvangjoshi** [comment]
Good to know. So, can I rerun my tests now?

**Comment by mbebenita** [comment]
Only if you need analyzer support. Errors when building the analyzer don't affect the runs.

**Comment by urvangjoshi** [comment]
Not sure I understand, isn't analyzer the one generating the compression performance report?
I thought that was the reason why some of the clips here didn't get any numbers (and so, not average numbers): https://arewecompressedyet.com/?job=palette_withTR%402017-01-27T02%3A24%3A37.556Z&job=palette_noTR%402017-01-27T02%3A26%3A23.126Z

**Comment by mbebenita** [comment]
No. The compression reports are produced by the AWCY backend and are not related to the analyzer. The Analyzer lets you view the encoded bit streams and inspect individual frames.

**Comment by urvangjoshi** [comment]
Oh, I see. Thanks for the explanation.
I'll create a separate issue for the problem I mentioned above.

Feel free to close this bug when the rebase is done.
