### ISSUE TITLE
analyzer: Inter ref frames marked as N/A

### ISSUE THREAD

**Issue by aconverse** [tdaede/awcy#139]
With the default experiments I'm often seeing inter ref frames marked as N/A in the analyzer. 

For instance in the top left superblock of frame 1 of:

https://arewecompressedyet.com/analyzer.html?maxFrames=4&decoder=https://arewecompressedyet.com/runs/bsize_dist@2017-03-29T23:18:27.564Z/js/decoder.js&decoderName=bsize_dist%402017-03-29T23%3A18%3A27.564Z&file=https://arewecompressedyet.com/runs/bsize_dist@2017-03-29T23:18:27.564Z/objective-1-fast/aspen_1080p_60f.y4m-63.ivf&decoder=https://arewecompressedyet.com/runs/bcropped_dist@2017-03-29T23:21:00.200Z/js/decoder.js&decoderName=bcropped_dist%402017-03-29T23%3A21%3A00.200Z&file=https://arewecompressedyet.com/runs/bcropped_dist@2017-03-29T23:21:00.200Z/objective-1-fast/aspen_1080p_60f.y4m-63.ivf

I'm seeing "Reference Frame: N/A, N/A" in the "Block Info" panel.

**Comment by mbebenita** [comment]
This problem is not just for inter ref frames, the code was displaying the second ref frame twice. Should be fixed in #140.
