### ISSUE TITLE
Have pictures comparing different daala/x264/x265 versions

### ISSUE THREAD

**Issue by mdinger** [tdaede/awcy#45]
Each daily build should upload pictures compressed with all the encoders for subjective comparison. For example, this [paper](http://people.xiph.org/~unlord/PCS2015/PCS2015.pdf) made comparisons between encoders via subjective analysis of a few reference pictures.

Say Daala March 3 and Daala July 15 were chosen for comparison. Then a column of reference daala March 3 encode pictures would on the left and likewise July 15 on the right (the same pictures would be side by side probably as thumbnails). Maybe CTRL-CLICK should open up the full pictures. Then, rather than saying the metrics aren't completely adequate, the encoder improvement could be directly compared on awcy.

**Comment by tdaede** [comment]
If anyone would like to work on this, I can help out. There's a couple different pieces needed:

1. a UI on AWCY
2. code on AWCY to invoke this new type of job
3. hosting for the files

We already have the ab_compare_*.sh scripts to actually generate the videos. Just need to be able to run it remotely on the AWS machines.

Hosting for the files can be done directly from the AWCY VM, at least for a while.

**Comment by mdinger** [comment]
Some of the [xiph reference media](https://wiki.xiph.org/Daala_Quickstart#Encoding_a_Video).

I might decide to play with this (no guarantees). I could probably figure out part 2 but I'm not sure about part 1.

**Comment by mdinger** [comment]
What goes in the `./aws.json` file? It won't build without it.

**Comment by mdinger** [comment]
@tdaede ^ Any tips?

**Comment by tdaede** [comment]
aws.json is the AWS keys used for starting and stopping machines. It doesn't do very much - I could make it optional, or I can send you some test keys.

Note that AWCY is currently split into two parts - the web frontend, and rd_tool.py in the rd_tool repository. The split is currently a bit awkward.

**Comment by mdinger** [comment]
@tdaede I guess sending test keys would be okay with me. Right now I'm just trying to get it running locally.

**Comment by mdinger** [comment]
This is fixed by https://github.com/tdaede/awcy/pull/49 . Further improvements should probably get their own issue.
